# Generated by Django 3.0.3 on 2020-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
